config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :books do
    member do
      get 'similar'
    end
  end
  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(params[:sort])
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(params.require(:book).permit(:name, :author, :genre, :rating))

    if @book.save
    redirect_to @book
  else
    render 'new'
  end
  end
  def edit
    @book = Book.find(params[:id])
  end
  def show
    @book = Book.find(params[:id])
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  def similar
    @book = Book.find(params[:id])
    @books = Book.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for :book, url: books_path do |f| %>

<%if @book.errors.any? %>
<div id = "error explanation">
  <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :author %>
  <%= f.text_field :author %>
</p>

<p>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
</p>

<p>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
</p>

<p>
  <%= f.submit %>
</p>
<%end%>

app/views/books/edit.html.erb
<h1> Edit Book </h1>
  <%= render 'form' %>
  <%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Library</h1>
<%= link_to "Add Book", new_book_path %>
<table>
  <tr>
    <th> <%=link_to "Name", :sort => 'name'%> </th>
    <th> <%= link_to "Author", :sort => 'author' %> </th>
    <th> <%= link_to "Genre", :sort => 'genre' %></th>
    <th> <%= link_to "Rating", :sort => 'rating' %></th>
  </tr>

<% @books.each do |book| %>
<tr>
  <td><%= book.name %></td>
  <td><%= book.author %></td>
  <td><%= book.genre %></td>
  <td><%= book.rating %></td>
  <td><%= link_to "similar books", similar_book_path(book) %></td>
  <td> <%= link_to "Edit", edit_book_path(book) %></td>
  <td> <%= link_to "Destroy!", book_path(book), method: :delete, data: {confirm: "are you sure?"} %> </td>
</tr>
<% end %>
</table>
<%= link_to "Back", books_path %>

app/views/books/new.html.erb
<h1>New Book </h1>

<%= render 'form' %>
<%= link_to "Back", books_path %>

app/views/books/show.html.erb
<p>
  <strong>Title: </strong>
  <%= @book.name %>
</p>

<p>
  <strong>Author: </strong>
  <%= @book.author || unknown%>
</p>

<p>
  <strong>Rating: </strong>
  <%= @book.rating %>
</p>

<%= link_to "Similar Books", similar_book_path(@book) %>
<%= link_to "Back", books_path %>
<%= link_to "Edit", edit_book_path(@book) %>

app/views/books/similar.html.erb
<h1>Books similar to <%= @book.name %></h1>
  <% usingBooks = @books.select{|book| book.genre.to_s == @book.genre.to_s}%>
  <% if usingBooks.size > 0 %>
<table>
  <tr>
    <th> Title </th>
    <th> Author </th>
    <th> Rating </th>
  </tr>
<% usingBooks.each do |book| %>
<% unless (book.name.to_s == @book.name.to_s && book.author.to_s == @book.author.to_s) %>
<tr>
  <td><%= book.name %></td>
  <td><%= book.author %></td>
  <td><%= book.genre %></td>
  <td><%= book.rating %></td>
</tr>
<%end%>
<%end%>
</table>
<%else%>
<p>We have no books similar to <%= @book.name %>. </p>
<%end%>
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<p> stuff will go here </p>

<%= link_to "My books", controller: 'books' %>
<%= link_to "Add Book", new_book_path %>